// @ts-check

/**
 * Every page under docs/commands/ is written by scripts/gen_pages.py, so the
 * reference is autogenerated here rather than listed by hand — otherwise a
 * command added upstream would need remembering in two places.
 *
 * The whole sidebar is generated from the docs tree, which matters for one
 * reason: only an autogenerated *category* applies the category-index
 * convention, where docs/commands/index.mdx becomes the category's own link
 * and is dropped from the item list. Writing the category by hand and pointing
 * its `link` at that same doc left it in the list as well, so the Overview page
 * sat immediately after itself and its "Next" button pointed back at itself.
 * The category's label and ordering live in docs/commands/_category_.json.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
