// @ts-check

/**
 * Every page under docs/commands/ is written by scripts/gen_pages.py, so the
 * reference is autogenerated here rather than listed by hand — otherwise a
 * command added upstream would need remembering in two places.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    'intro',
    'global-flags',
    {
      type: 'category',
      label: 'Command reference',
      link: {type: 'doc', id: 'commands/index'},
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'commands',
        },
      ],
    },
  ],
};

export default sidebars;
